// This file is generated by npm run build:icons

export type AllIconTypes =
	| "icons/arrow"
	| "icons/chip-logo"
	| "icons/exchange-arrows"
	| "icons/facebook-icon"
	| "icons/handset"
	| "icons/instagram-icon"
	| "icons/login-icon"
	| "icons/smartphone"
	| "icons/twitter-icon"
	| "icons/youtube-icon";
